import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import Header from "@/components/header";

const noto_Sans_JP = Noto_Sans_JP();

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body
				className={`${noto_Sans_JP.className} antialiased h-screen flex flex-col`}
			>
				<Header />
				<main className="flex-1 overflow-auto">{children}</main>
			</body>
		</html>
	);
}
