import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "@/app/globals.css";
import Header from "@/components/header";

const noto_Sans_JP = Noto_Sans_JP();

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body
				className={`${noto_Sans_JP.className} antialiased min-h-screen flex flex-col`}
			>
				<Header />
				{children}
			</body>
		</html>
	);
}
